version: '3.3'

services:
  chat:
    build: .
    command: python -u /app/runserver.py
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: simple_chat
    ports:
      - 27017:27017
